typedef char * string_stream;
typedef enum calc_status_enum calc_status;
typedef enum command_status_enum command_status;
typedef enum stream_status_enum stream_status;
typedef struct chemdb_struct chemdb;
typedef struct command_struct command;
typedef struct element_struct element_data;
typedef struct element_struct2 element_data2;
typedef struct sfv_struct sfv;
typedef unsigned chemdb_id;
typedef unsigned element_id;
typedef unsigned client_index;
